# Создаём namespace для приложения
---
apiVersion: v1
kind: Namespace
metadata:
  name: mindbox
...

# Для примера приложения возьмём образ nginx версии 1.13.
# Приложение будет запускаться в одном экземпляре.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application
  name: scalable-with-cronjob
  namespace: mindbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nginx:1.13
          resources:
            limits:
              memory: 128Mi
              cpu: 0.5 # Это много больше, чем необходимые 0.1
            requests:
              memory: 128Mi
              cpu: 0.1
          startupProbe:
            httpGet:
              path: /
              port: 80
            # Приолжению требуется 5-10 секунд для старта.
            # Значит, будем проверять состояние приложения каждые 2 секунды.
            # Всего будет допустимо 5 проваленных проверок.
            # Если через 12 секунд под не запустится, то он будет убит и запущен заново
            periodSeconds: 2
            failureThreshold: 5
      affinity:
        # Реазиуем максимальную отказоустойчивость путём запрета запуска двух подов на одной ноде
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - scalable-with-cronjob
...

# Создаём ServiceAccount под которым будем менять количество запущенных подов
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scalable-sa
  namespace: mindbox
...

# Создаём роль для него
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scalable-role
  namespace: mindbox
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["*"]
...

# Предоставляем права, указаныне в роли, севисаккаунту
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scalable-rb
  namespace: mindbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scalable-role
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: scalable-sa
...

# Запланируем запуск дополнительных подов в 10:00 МСК-3 (UTS)
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: scaler-up
  name: scaler-up
  namespace: mindbox
spec:
  schedule: "0 10 * * *"
  jobTemplate:
    metadata:
      labels:
        app: scaler
    spec:
      template:
        spec:
          serviceAccountName: scalable-sa
          automountServiceAccountToken: true
          restartPolicy: OnFailure
          containers:
            - name: scalable-up
              image: bitnami/kubectl
              command: ["kubectl"]
              args: ["scale", "deployment", "scalable-with-cronjob", "--replicas", "4"]
...

# Запланируем удаление лишних подов в 20:00 МСК-3 (UTS)
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: scaler-down
  name: scaler-down
  namespace: mindbox
spec:
  schedule: "0 20 * * *"
  jobTemplate:
    metadata:
      labels:
        app: scaler
    spec:
      template:
        spec:
          serviceAccountName: scalable-sa
          automountServiceAccountToken: true
          restartPolicy: OnFailure
          containers:
            - name: scalable-up
              image: bitnami/kubectl
              command: ["kubectl"]
              args: ["scale", "deployment", "scalable-with-cronjob", "--replicas", "1"]
...